### ISSUE TITLE
Destination Image Displays out of container

### ISSUE THREAD

**Issue by pastelApe** [CMSC495-Team1/Team1_TripPlanner#27] opened 2024-11-18 18:47 UTC
If you go to create a trip and hit cancel, this is what the images looks like on my end once back at the Plan Trip page.

<img width="1405" alt="Screenshot 2024-11-18 at 1 45 29 PM" src="https://github.com/user-attachments/assets/b5bec91c-a253-4de6-af3c-c665fba190d7">

**Comment by GChel31** [comment] 2024-11-18 19:00
Didnt mean to close the issue, fat-fingered the wrong button

**Comment by GChel31** [comment] 2024-11-18 22:18
Hey, I checked this and couldn't reproduce it. The cancel buttons shouldn't have any actions tied to them at the moment, so I'm not sure why that is happening.

**Comment by pastelApe** [comment] 2024-11-18 22:35
Hitting cancel doesn’t take you back to the plan trip page?

**Comment by GChel31** [comment] 2024-11-19 01:31
It looks like my repo didn't have some of the recent updates. I'm working on a fix now

**Comment by GChel31** [comment] 2024-11-19 01:40
Should work now with my most recent merge

**Closed by GChel31** 2024-11-19 01:40 UTC
Labels: bug
